[package]
name = "vp3_ifm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdnative = "0.10.0"
serde_json = "1.0.79"
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["cdylib"]